[openai]
SECRET_KEY="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"

[server]
UPLOAD_FOLDER="uploaded_images"
STATE_FOLDER="state_data"

[sciebo]
SCIEBO_USERNAME="murtaza.fakhruddin@tu-dortmund.de"
SCIEBO_PASSWORD="VXNNU-YDUQJ-XMLMZ-MNECJ" #this is app password
SCIEBO_APPNAME="medical_ai"
SCIEBO_IMAGE_BASEURL= "https://tu-dortmund.sciebo.de/remote.php/dav/files/murtaza.fakhruddin@tu-dortmund.de/medical_ai/images/"
SCIEBO_STATE_BASEURL= "https://tu-dortmund.sciebo.de/remote.php/dav/files/murtaza.fakhruddin@tu-dortmund.de/medical_ai/state_data/"